# Generated by Django 4.1.2 on 2024-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_statistics_houseplant_statistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='statistic_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the category', max_length=20),
        ),
        migrations.AddField(
            model_name='statistics',
            name='description',
            field=models.TextField(default='', help_text='Enter a brief description of the statistic'),
        ),
    ]
