# Generated by Django 4.1.2 on 2024-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_statistic_name_statistics_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseplant_statistic',
            name='StatisticID',
        ),
        migrations.AddField(
            model_name='houseplant_statistic',
            name='careDifficulty',
            field=models.IntegerField(default=0, help_text='Enter the care difficulty of the plant'),
        ),
        migrations.AddField(
            model_name='houseplant_statistic',
            name='popularity',
            field=models.IntegerField(default=0, help_text='Enter the popularity of the plant'),
        ),
        migrations.AddField(
            model_name='houseplant_statistic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the price of the plant', max_digits=10),
        ),
    ]
