# Generated by Django 4.1.2 on 2024-04-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_houseplant_houseplant_scientf_f4db7d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='care',
            index=models.Index(fields=['careID'], name='care_careID_ecfa5d_idx'),
        ),
    ]
