# Generated by Django 4.1.2 on 2024-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_houseplant_statistic_houseplant__housepl_38c0ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplant_statistic',
            name='searchCount',
            field=models.IntegerField(default=0, help_text='Enter the search count of the plant'),
        ),
    ]
